name: Build and Deploy to Azure Web App Slot

on:
  push:
    branches:
      - main  # Adjust this as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'  # Use the version you need

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Run tests with dotnet
      run: dotnet test --no-build --verbosity normal

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Use your secret

    - name: Deploy to Azure Web App Slot
      id: deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'blueberryapp'  # Name of your Azure Web App
        slot-name: 'blueberryapi'  # Name of the deployment slot
        package: '.'  # Path to the package to deploy, typically the root of the repo
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Use your publish profile secret
